### ISSUE TITLE
logging in with correct email does not work (=error)

### ISSUE THREAD

**Issue by carlbalmer** [pfadipatria/hitobito_patria#3]
On branch ldap_changes2
The issue occurs when logging in with fidelio@pfadipatria.com and the approprtate password.
This causes this error:
ActiveRecord::RecordInvalid in Devise::SessionsController#create
Gültigkeitsprüfung ist fehlgeschlagen: Bitte geben Sie einen Namen ein.
Becuse the same code seems to run on some systems but not on oters, we think it may be because of different gems.

The terminal output of the server shows this (when logging im with email):

Started POST "/de/users/sign_in" for 127.0.0.1 at 2015-03-20 11:23:08 +0100
Processing by Devise::SessionsController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"apj5sj8lzpQ1UId2J46F1c8D1ZUpmEZUZJeC9SfMsh0=", "person"=>{"email"=>"fidelio@pfadipatria.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "button"=>"", "locale"=>"de"}
[1m[35mPerson Load (0.4ms)[0m  SELECT  "people".\* FROM "people"  WHERE "people"."email" = 'fidelio@pfadipatria.com'  ORDER BY "people"."id" ASC LIMIT 1
LDAP:[0m LDAP dn lookup: mail=fidelio@pfadipatria.com
LDAP:[0m LDAP search for login: mail=fidelio@pfadipatria.com
LDAP:[0m LDAP search yielded 1 matches
LDAP:[0m Authorizing user uid=fidelio,ou=people,dc=pfadipatria,dc=com
LDAP:[0m LDAP dn lookup: mail=fidelio@pfadipatria.com
LDAP:[0m LDAP search for login: mail=fidelio@pfadipatria.com
LDAP:[0m LDAP search yielded 1 matches
[1m[36m (0.1ms)[0m  [1mbegin transaction[0m
[1m[35mPerson Exists (0.1ms)[0m  SELECT  1 AS one FROM "people"  WHERE "people"."email" = 'fidelio@pfadipatria.com' LIMIT 1
[1m[36m (0.1ms)[0m  [1mrollback transaction[0m
Completed 422 Unprocessable Entity in 647ms
[1m[35mPerson Load (0.3ms)[0m  SELECT  "people".\* FROM "people"  WHERE "people"."email" = 'fidelio@pfadipatria.com'  ORDER BY "people"."id" ASC LIMIT 1
 *\* [Airbrake] Notice was not sent due to configuration:  
  Environment Monitored? false  
  API key set? false
ActiveRecord::RecordInvalid (Gültigkeitsprüfung ist fehlgeschlagen: Bitte geben Sie einen Namen ein.):

**Comment by hairmare** [comment]
You can reset your changes to the gems by resetting `Gemfile.lock` and rerunning `bundle install`. You might also need to reload the db fixtures to ensure that you all have the same state.

Also, your changes in the ldap_changes2 branch seem to change an awful lot. That might be part of the problem.

We don't need nickname in core to get replaced at every occurrence (ie. `app/views/devise/sessions/new.html.haml` looks like some frontendy html form). All we need is for the attribute responsible for syncing users to ldap to hinge on email.

The error looks like you'll have to initialise new ldap-users being created in hitobito with a name. You should be able to grab that from the users record in ldap.

**Comment by carlbalmer** [comment]
I think we found the cause.
The error is caused, when the person logging in does not exist in the local db, or the persons email is not set.

**Comment by g1raffi** [comment]
"We don't need nickname in core to get replaced at every occurrence (ie. app/views/devise/sessions/new.html.haml looks like some frontendy html form). All we need is for the attribute responsible for syncing users to ldap to hinge on email."

This is just for changing the html-login form to the login value. It does only ask the user for his email instead of his nickname to log-in.

**Comment by hairmare** [comment]
@snd1 Now I see, changing the login form is fine and makes sense.

**Comment by g1raffi** [comment]
@hairmare Funny thing, when I change the login form now back, to [:nickname] it works just fine to log in... It doesn't make any sense to me, because this is just a view file and worked absolutely fine.

**Comment by hairmare** [comment]
@snd1 That actually makes sense as well (at least for users that are already in hitobito). If keeping the nickname in the form works, I'd prefer that. We would then manually ensure that users that have an ldap login are created in both systems.

Our use case is that people will have an entry in hitobito long before they get a user. As soon as they get into a leader position we change their email in hitobito and add them to ldap at the same time. From that point on they will be able to login using their credentials.

**Comment by g1raffi** [comment]
@hairmare I think you missunderstood, just to see if we are on the same level: It does makes sense, that logging in with the email-attribute does not work when the html form expects an email entry?

**Comment by hairmare** [comment]
@snd1 Yupp, there is probably some kind of misunderstanding here.

Are users able to user their email instead of a nickname without changes to the form? I think that's what we're after.

Also, I feel like I'm micromanaging this a bit to much. Feel free to implement what makes sense and we'll look into it during the next sprint review meeting.

**Comment by g1raffi** [comment]
It's strange to me. Last week the whole thing worked without any problems. Now it seems like when changing the label of the login form from "Pfadiname" to "Hauptemail" it does not work at all. But when the label is still "Pfadiname" the user is able to log in with his email just fine.

**Comment by hairmare** [comment]
Closing this since it is outdated.
